//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
// Parameters:
//
//   float4x4 Projection;
//   float TexCoordTransformAngle_0;
//   float Time;
//   float4x4 View;
//
//
// Registers:
//
//   Name                     Reg   Size
//   ------------------------ ----- ----
//   View                     c0       4
//   Projection               c4       4
//   TexCoordTransformAngle_0 c8       1
//   Time                     c9       1
//
//
// Default values:
//
//   View
//     c0   = { 0, 0, 0, 0 };
//     c1   = { 0, 0, 0, 0 };
//     c2   = { 0, 0, 0, 0 };
//     c3   = { 0, 0, 0, 0 };
//
//   Projection
//     c4   = { 0, 0, 0, 0 };
//     c5   = { 0, 0, 0, 0 };
//     c6   = { 0, 0, 0, 0 };
//     c7   = { 0, 0, 0, 0 };
//
//   TexCoordTransformAngle_0
//     c8   = { 1, 0, 0, 0 };
//
//   Time
//     c9   = { 0, 0, 0, 0 };
//

    preshader
    mul r0, c4.x, c0
    mul r2, c4.y, c1
    add r1, r0, r2
    mul r2, c4.z, c2
    add r0, r1, r2
    mul r1, c4.w, c3
    add c0, r0, r1
    mul r0, c5.x, c0
    mul r2, c5.y, c1
    add r1, r0, r2
    mul r2, c5.z, c2
    add r0, r1, r2
    mul r1, c5.w, c3
    add c1, r0, r1
    mul r0, c6.x, c0
    mul r2, c6.y, c1
    add r1, r0, r2
    mul r2, c6.z, c2
    add r0, r1, r2
    mul r1, c6.w, c3
    add c2, r0, r1
    mul r0, c7.x, c0
    mul r2, c7.y, c1
    add r1, r0, r2
    mul r2, c7.z, c2
    add r0, r1, r2
    mul r1, c7.w, c3
    add c3, r0, r1
    mul r0.w, c8.x, c9.x
    mul r1.w, r0.w, (0.159154939)
    add r0.xy, r1.w, (0.25, 0.5)
    frc r1.xy, r0.xy
    mul r0.xy, (6.28318548, 6.28318548), r1.xy
    add r1.xy, (-3.14159274, -3.14159274), r0.xy
    mul r0.xy, r1.xy, r1.xy
    mul r1.xy, (-2.52398518e-007, -2.52398518e-007), r0.xy
    add r2.xy, (2.47609e-005, 2.47609e-005), r1.xy
    mul r1.xy, r0.xy, r2.xy
    add r2.xy, (-0.0013888397, -0.0013888397), r1.xy
    mul r1.xy, r0.xy, r2.xy
    add r2.xy, (0.0416666418, 0.0416666418), r1.xy
    mul r1.xy, r0.xy, r2.xy
    add r2.xy, (-0.499999996, -0.499999996), r1.xy
    mul r1.xy, r0.xy, r2.xy
    add r0.xy, (1, 1), r1.xy
    mov c4.x, r0.x
    mov c5.x, r0.y

// approximately 47 instructions used
//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
// Parameters:
//
//   float3 ColorEmissive;
//   
//   struct
//   {
//       float IsEnabled;
//       float4 Color;
//       float RangeStart;
//       float OneOverRangeDelta;
//
//   } Fog;
//   
//   struct
//   {
//       float4 ScaleUV_OffsetUV;
//
//   } Shroud;
//   
//   float TexCoordTransformU_0;
//   float TexCoordTransformU_1;
//   float TexCoordTransformU_2;
//   float TexCoordTransformV_0;
//   float TexCoordTransformV_1;
//   float TexCoordTransformV_2;
//   float4x3 ViewI;
//   float4x3 World;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   Fog                  c6       4
//   World                c10      3
//   ViewI                c13      3
//   ColorEmissive        c16      1
//   TexCoordTransformU_0 c17      1
//   TexCoordTransformV_0 c18      1
//   TexCoordTransformU_1 c19      1
//   TexCoordTransformV_1 c20      1
//   TexCoordTransformU_2 c21      1
//   TexCoordTransformV_2 c22      1
//   Shroud               c23      1
//
//
// Default values:
//
//   Fog
//     c6   = { 0, 0, 0, 0 };
//     c7   = { 1, 1, 1, 1 };
//     c8   = { 0, 0, 0, 0 };
//     c9   = { 0.001, 0, 0, 0 };
//
//   World
//     c10  = { 0, 0, 0, 0 };
//     c11  = { 0, 0, 0, 0 };
//     c12  = { 0, 0, 0, 0 };
//
//   ViewI
//     c13  = { 0, 0, 0, 0 };
//     c14  = { 0, 0, 0, 0 };
//     c15  = { 0, 0, 0, 0 };
//
//   ColorEmissive
//     c16  = { 1, 1, 1, 0 };
//
//   TexCoordTransformU_0
//     c17  = { 0.5, 0, 0, 0 };
//
//   TexCoordTransformV_0
//     c18  = { 0.5, 0, 0, 0 };
//
//   TexCoordTransformU_1
//     c19  = { 0.5, 0, 0, 0 };
//
//   TexCoordTransformV_1
//     c20  = { 0.5, 0, 0, 0 };
//
//   TexCoordTransformU_2
//     c21  = { 0.5, 0, 0, 0 };
//
//   TexCoordTransformV_2
//     c22  = { 0.5, 0, 0, 0 };
//
//   Shroud
//     c23  = { 1, 1, 0, 0 };
//

    vs_1_1
    def c24, 1, 0, 100, 0
    def c25, 0.5, 1.5, 2.5, 0
    dcl_position v0
    dcl_color v1
    dcl_texcoord v2
    mad r1, v0.xyzx, c24.xxxy, c24.yyyx
    mov r0.w, c24.x
    dp4 r0.z, r1, c12
    dp4 r0.x, r1, c10
    dp4 r0.y, r1, c11
    dp4 oPos.x, r0, c0
    dp4 oPos.y, r0, c1
    dp4 oPos.z, r0, c2
    mov r1.x, c13.w
    mov r1.y, c14.w
    mov r1.z, c15.w
    dp4 oPos.w, r0, c3
    add r1.xyz, r0, -r1
    mul oD0.xyz, v1, c16
    dp3 r1.x, r1, r1
    add r0.xy, r0, c23.zwzw
    rsq r0.w, r1.x
    mul oT2.xy, r0, c23
    rcp r0.w, r0.w
    mov r1.z, c21.x
    mov r1.w, c22.x
    add r0.w, r0.w, -c8.x
    add r1.xy, -r1.zwzw, v2
    mul r2.w, r1.y, c4.x
    mul r2.xy, r1, c5.x
    mad r0.x, r1.x, c5.x, r2.w
    mad r0.y, r1.x, -c4.x, r2.y
    mul r2.w, r0.w, c9.x
    add r0.xy, r1.zwzw, r0
    mad r0.z, r1.y, -c4.x, r2.x
    mad r0.w, r1.x, c4.x, r2.y
    add r0.zw, r1, r0
    mul r1.w, v1.w, c24.z
    add r0, r0, -v2.xyxy
    slt r2.xyz, r1.w, c25
    mov r3.z, c19.x
    mov r3.w, c20.x
    mad r1, r2.z, r0, v2.xyxy
    add r3.xy, -r3.zwzw, v2
    mul r0.w, r3.y, c4.x
    mul r4.xy, r3, c5.x
    mad r0.x, r3.x, c5.x, r0.w
    mad r0.y, r3.x, -c4.x, r4.y
    mad r0.z, r3.y, -c4.x, r4.x
    mad r0.w, r3.x, c4.x, r4.y
    add r0.xy, r3.zwzw, r0
    add r0.zw, r3, r0
    max r3.w, r2.w, c24.y
    add r0, -r1, r0
    mov r2.z, c17.x
    mov r2.w, c18.x
    mad r1, r2.y, r0, r1
    add r3.xy, -r2.zwzw, v2
    mul r0.w, r3.y, c4.x
    mul r4.xy, r3, c5.x
    mad r0.x, r3.x, c5.x, r0.w
    mad r0.y, r3.x, -c4.x, r4.y
    mad r0.z, r3.y, -c4.x, r4.x
    mad r0.w, r3.x, c4.x, r4.y
    add r0.xy, r2.zwzw, r0
    add r0.zw, r2, r0
    min r2.w, r3.w, c24.x
    add r0, -r1, r0
    mov r3.w, c24.x
    mad oD1.x, c6.x, -r2.w, r3.w
    mad r0, r2.x, r0, r1
    mov oT0.xy, r0
    mov oT1.xy, r0.zwzw

// approximately 68 instruction slots used

