//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
// Parameters:
//
//   struct
//   {
//       float3 Color;
//       float3 Direction;
//
//   } DirectionalLight[3];
//   
//   float3 NoCloudMultiplier;
//   float Time;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   DirectionalLight  c0       1
//   NoCloudMultiplier c1       1
//   Time              c2       1
//
//
// Default values:
//
//   DirectionalLight
//     c0   = { 1.247, 1.207, 1.043, 0 };
//
//   NoCloudMultiplier
//     c1   = { 1, 1, 1, 0 };
//
//   Time
//     c2   = { 0, 0, 0, 0 };
//

    preshader
    mul c20.xyz, c0.xyz, c1.xyz
    mul c21.x, c2.x, (0.004)

// approximately 2 instructions used
//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
// Parameters:
//
//   float3 AmbientLightColor;
//   
//   struct
//   {
//       float3 Color;
//       float3 Direction;
//
//   } DirectionalLight[3];
//   
//   struct
//   {
//       float IsEnabled;
//       float4 Color;
//       float RangeStart;
//       float OneOverRangeDelta;
//
//   } Fog;
//   
//   float4x3 ViewI;
//   float4x3 World;
//   float4x4 WorldViewProjection;
//
//
// Registers:
//
//   Name                Reg   Size
//   ------------------- ----- ----
//   DirectionalLight    c0       6
//   Fog                 c6       4
//   WorldViewProjection c10      4
//   World               c14      3
//   ViewI               c17      3
//   AmbientLightColor   c22      1
//
//
// Default values:
//
//   DirectionalLight
//     c0   = { 1.247, 1.207, 1.043, 0 };
//     c1   = { 0.62914, -0.34874, 0.69465, 0 };
//     c2   = { 0.745, 0.831, 0.894, 0 };
//     c3   = { -0.32877, 0.90329, 0.27563, 0 };
//     c4   = { 0.69, 0.667, 0.69, 0 };
//     c5   = { -0.80704, -0.58635, 0.06975, 0 };
//
//   Fog
//     c6   = { 0, 0, 0, 0 };
//     c7   = { 1, 1, 1, 1 };
//     c8   = { 0, 0, 0, 0 };
//     c9   = { 0.001, 0, 0, 0 };
//
//   WorldViewProjection
//     c10  = { 0, 0, 0, 0 };
//     c11  = { 0, 0, 0, 0 };
//     c12  = { 0, 0, 0, 0 };
//     c13  = { 0, 0, 0, 0 };
//
//   World
//     c14  = { 0, 0, 0, 0 };
//     c15  = { 0, 0, 0, 0 };
//     c16  = { 0, 0, 0, 0 };
//
//   ViewI
//     c17  = { 0, 0, 0, 0 };
//     c18  = { 0, 0, 0, 0 };
//     c19  = { 0, 0, 0, 0 };
//
//   AmbientLightColor
//     c22  = { 0.3, 0.3, 0.3, 0 };
//

    vs_1_1
    def c23, 1, 0, 25, 0.00300000003
    def c24, 0.337500006, 0.75, 0.524999976, 0
    dcl_position v0
    dcl_texcoord v1
    dcl_color v2
    mad r0, v0.xyzx, c23.xxxy, c23.yyyx
    dp4 r2.z, r0, c16
    mov r4.x, c17.w
    mov r4.y, c18.w
    mov r4.z, c19.w
    dp4 r2.x, r0, c14
    dp4 r2.y, r0, c15
    add r6.xyz, -r2, r4
    dp4 oPos.x, r0, c10
    dp3 r1.x, r6, r6
    dp4 oPos.y, r0, c11
    rsq r2.w, r1.x
    dp4 oPos.z, r0, c12
    mad r3.xyz, r6, r2.w, c3
    dp4 oPos.w, r0, c13
    dp3 r3.x, r3, r3
    mov r0, c23
    mad r1.xzw, c3.z, r0.xyyy, r0.yyzz
    rsq r3.w, r3.x
    add r5.xyz, r2, -r4
    mul r1.y, r3.z, r3.w
    lit r1, r1
    mad r7.xyz, r6, r2.w, c1
    mul r3.xyz, r1.y, c2
    dp3 r1.x, r7, r7
    mul r4.xyz, r1.z, c2
    rsq r1.w, r1.x
    mul r1.y, r7.z, r1.w
    mad r1.xzw, c1.z, r0.xyyy, r0.yyzz
    mad r6.xyz, r6, r2.w, c5
    lit r1, r1
    mad r3.xyz, c20, r1.y, r3
    dp3 r1.x, r6, r6
    mad r4.xyz, c20, r1.z, r4
    rsq r1.w, r1.x
    mul r1.y, r6.z, r1.w
    dp3 r5.x, r5, r5
    mad r1.xzw, c5.z, r0.xyyy, r0.yyzz
    rsq r2.w, r5.x
    lit r1, r1
    rcp r1.w, r2.w
    mad r3.xyz, c4, r1.y, r3
    add r1.w, r1.w, -c8.x
    mad r1.xyz, c4, r1.z, r4
    mul r1.w, r1.w, c9.x
    add r3.xyz, r3, c22
    max r1.w, r1.w, c23.y
    mad r1.xyz, r1, c24, r3
    min r1.w, r1.w, c23.x
    mul oD0.xyz, r1, v2
    mad oD1.x, c6.x, -r1.w, r0.x
    mad oT1.xy, r2, r0.w, c21.x
    mad oT2.xy, r2, r0.w, -c21.x
    mov oD0.w, v2.w
    mov oT0.xy, v1

// approximately 55 instruction slots used

//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
// Parameters:
//
//   sampler2D GlowSamplerSampler;
//   float4 HalfColorDelta;
//   sampler2D MaskSamplerSampler;
//   float4 MaxColorDelta;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   MaxColorDelta      c0       1
//   HalfColorDelta     c1       1
//   MaskSamplerSampler s0       1
//   GlowSamplerSampler s1       1
//   GlowSamplerSampler s2       1
//
//
// Default values:
//
//   MaxColorDelta
//     c0   = { 1, 1, 1, 0 };
//
//   HalfColorDelta
//     c1   = { -0.33, -0.33, -0.33, -0 };
//

    ps_1_1
    def c2, 1, -0, -0, 1
    tex t0
    tex t1
    tex t2
    mul r0, t1, t2
    dp3 r0, c2, r0
    mad r0, c2.w, r0.w, r0
    mad r0, r0, c0, c1
    mad_sat r0, t0, v0, r0

// approximately 8 instruction slots used (3 texture, 5 arithmetic)
